name: flutter_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_analytics: ^9.3.8
  firebase_core: ^1.24.0
  firebase_messaging: ^13.0.4
  firebase_remote_config: ^2.0.20
  flutter_local_notifications: ^12.0.0
  get: ^4.6.5
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
