name: flutter_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  firebase_analytics: ^10.0.5
  firebase_auth: ^4.1.2
  firebase_core: ^2.2.0

  firebase_dynamic_links: ^5.0.5
  firebase_messaging: ^14.1.0
  firebase_remote_config: ^3.0.5
  flutter_local_notifications: ^12.0.0

  get: ^4.6.5
  image_picker: ^0.8.5+3
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
