// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS0Xr3LWPMRukWBMAiG8fhlbrgPNWrbSk',
    appId: '1:799757141641:web:f08ed218aaab67351fe858',
    messagingSenderId: '799757141641',
    projectId: 'flutter-beginner-fecf8',
    authDomain: 'flutter-beginner-fecf8.firebaseapp.com',
    storageBucket: 'flutter-beginner-fecf8.appspot.com',
    measurementId: 'G-7TW1FGDDRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgXYXj-cj_Z-wRS8VTddABnuqCwvu0X9c',
    appId: '1:799757141641:android:8ffe41c981de44231fe858',
    messagingSenderId: '799757141641',
    projectId: 'flutter-beginner-fecf8',
    storageBucket: 'flutter-beginner-fecf8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9ULDEJzmehmdIjeUbuJ6hY1np8-nFdbA',
    appId: '1:799757141641:ios:8d864d6b72253e061fe858',
    messagingSenderId: '799757141641',
    projectId: 'flutter-beginner-fecf8',
    storageBucket: 'flutter-beginner-fecf8.appspot.com',
    iosClientId: '799757141641-auqplid2ejqetglo8o3oif5fnts3pk0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9ULDEJzmehmdIjeUbuJ6hY1np8-nFdbA',
    appId: '1:799757141641:ios:8d864d6b72253e061fe858',
    messagingSenderId: '799757141641',
    projectId: 'flutter-beginner-fecf8',
    storageBucket: 'flutter-beginner-fecf8.appspot.com',
    iosClientId: '799757141641-auqplid2ejqetglo8o3oif5fnts3pk0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
